version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: stock_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock_db
    ports:
      - "5433:5433"
    command: -p 5433
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
